#!/usr/bin/env bash
# Mirror Mind hook wrapper — GENERATED by scripts/ts5/generate_hook_wrappers.sh.
# Edit the generator, never this file: eleven wrappers share these bytes and
# differ only in the hook name below (CV22.DS10.TS5, decision D4).
#
# Resolve the repository from THIS FILE, never from the cwd: a runtime spawns
# hooks from whatever directory the session is in.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$HERE/../.." && pwd -P)"
HOOK="claude:session-start"

# Find Node. /usr/bin/python3 exists on every macOS; node usually lives under
# nvm or Homebrew and is NOT on the PATH of a GUI-launched runtime. The Python
# hooks could end in `|| true` because they always found their interpreter;
# the same silence here would hide a new failure — no logging, no inject, no
# close tail — that a user would meet weeks later as "Mirror stopped
# remembering". So an unresolvable Node is RECORDED, never swallowed.
NODE="${MIRROR_NODE:-}"
if [ -z "$NODE" ] || [ ! -x "$NODE" ]; then
  NODE="$(command -v node 2>/dev/null || true)"
fi
for candidate in "$HOME/.nvm/current/bin/node" /opt/homebrew/bin/node /usr/local/bin/node; do
  [ -n "$NODE" ] && break
  [ -x "$candidate" ] && NODE="$candidate"
done

if [ -z "$NODE" ]; then
  HOME_DIR="${MIRROR_HOME:-$HOME/.mirror-minds/${MIRROR_USER:-default}}"
  mkdir -p "$HOME_DIR" 2>/dev/null \
    && printf '%s %s: node not found on PATH; hook skipped. Set MIRROR_NODE.\n' \
       "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$HOOK" >> "$HOME_DIR/hooks.log" 2>/dev/null
  exit 0
fi

exec "$NODE" --no-warnings --env-file-if-exists="$REPO_ROOT/.env" \
  "$REPO_ROOT/ts/src/hooks/main.ts" "$HOOK"
