#!/usr/bin/env bash
# Generate every Mirror hook wrapper from one template (CV22.DS10.TS5, D4).
#
# Twelve wrappers across four runtimes. They differ by exactly one word -- the
# hook name -- and `hookWrappers.test.ts` asserts that, because copies that can
# differ in only one place cannot drift the way the skill copies did (CR071:
# eleven skills reaching the front door on Pi while still calling Python on
# Claude Code and the published plugin, for commands flipped as far back as
# DS3, and nothing failed because Python answered correctly).
#
# Usage:
#   bash scripts/ts5/generate_hook_wrappers.sh          # write
#   bash scripts/ts5/generate_hook_wrappers.sh --check  # report drift, exit 1

set -uo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
CHECK="${1:-}"

# wrapper path | hook name | depth from the wrapper to the repository root
WRAPPERS=$(cat <<'EOF'
.claude/hooks/session-start.sh|claude:session-start|../..
.claude/hooks/log-user-prompt.sh|claude:user-prompt|../..
.claude/hooks/log-session-end.sh|claude:session-end|../..
.claude/hooks/mirror-inject.sh|claude:inject|../..
.gemini/hooks/session-start.sh|gemini:session-start|../..
.gemini/hooks/log-user.sh|gemini:log-user|../..
.gemini/hooks/log-assistant.sh|gemini:log-assistant|../..
.gemini/hooks/session-end.sh|gemini:session-end|../..
plugins/mirror-mind/hooks/session-start.sh|claude:session-start|../../..
plugins/mirror-mind/hooks/log-user-prompt.sh|claude:user-prompt|../../..
plugins/mirror-mind/hooks/log-session-end.sh|claude:session-end|../../..
plugins/mirror-mind/hooks/mirror-inject.sh|claude:inject|../../..
EOF
)

render() {
  local hook="$1" depth="$2"
  cat <<EOF
#!/usr/bin/env bash
# Mirror Mind hook wrapper — GENERATED by scripts/ts5/generate_hook_wrappers.sh.
# Edit the generator, never this file: eleven wrappers share these bytes and
# differ only in the hook name below (CV22.DS10.TS5, decision D4).
#
# Resolve the repository from THIS FILE, never from the cwd: a runtime spawns
# hooks from whatever directory the session is in.
set -uo pipefail
HERE="\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="\$(cd "\$HERE/$depth" && pwd -P)"
HOOK="$hook"

# Find Node. /usr/bin/python3 exists on every macOS; node usually lives under
# nvm or Homebrew and is NOT on the PATH of a GUI-launched runtime. The Python
# hooks could end in \`|| true\` because they always found their interpreter;
# the same silence here would hide a new failure — no logging, no inject, no
# close tail — that a user would meet weeks later as "Mirror stopped
# remembering". So an unresolvable Node is RECORDED, never swallowed.
NODE="\${MIRROR_NODE:-}"
if [ -z "\$NODE" ] || [ ! -x "\$NODE" ]; then
  NODE="\$(command -v node 2>/dev/null || true)"
fi
for candidate in "\$HOME/.nvm/current/bin/node" /opt/homebrew/bin/node /usr/local/bin/node; do
  [ -n "\$NODE" ] && break
  [ -x "\$candidate" ] && NODE="\$candidate"
done

if [ -z "\$NODE" ]; then
  HOME_DIR="\${MIRROR_HOME:-\$HOME/.mirror-minds/\${MIRROR_USER:-default}}"
  mkdir -p "\$HOME_DIR" 2>/dev/null \\
    && printf '%s %s: node not found on PATH; hook skipped. Set MIRROR_NODE.\\n' \\
       "\$(date -u +%Y-%m-%dT%H:%M:%SZ)" "\$HOOK" >> "\$HOME_DIR/hooks.log" 2>/dev/null
  exit 0
fi

exec "\$NODE" --no-warnings --env-file-if-exists="\$REPO_ROOT/.env" \\
  "\$REPO_ROOT/ts/src/hooks/main.ts" "\$HOOK"
EOF
}

status=0
while IFS='|' read -r path hook depth; do
  [ -z "$path" ] && continue
  target="$REPO_ROOT/$path"
  rendered="$(render "$hook" "$depth")"
  if [ "$CHECK" = "--check" ]; then
    if [ ! -f "$target" ] || [ "$(cat "$target")" != "$rendered" ]; then
      echo "drift: $path"
      status=1
    fi
  else
    mkdir -p "$(dirname "$target")"
    printf '%s\n' "$rendered" > "$target"
    chmod +x "$target"
  fi
done <<< "$WRAPPERS"

if [ "$CHECK" = "--check" ]; then
  [ "$status" -eq 0 ] && echo "hook wrappers: in sync."
  exit "$status"
fi
echo "hook wrappers: generated."
