#!/usr/bin/env bash
# Generate every Mirror hook wrapper from one template (CV22.DS10.TS5, D4).
#
# The wrappers differ by exactly two things -- the hook name and the depth
# from the wrapper to the repository root -- and `hooks.test.ts` asserts that,
# because copies that can differ in only one place cannot drift the way the
# skill copies did (CR071: eleven skills reaching the front door on Pi while
# still calling Python on Claude Code and the published plugin, for commands
# flipped as far back as DS3, and nothing failed because Python answered
# correctly).
#
# The template is a QUOTED heredoc with two placeholders, @HOOK@ and @DEPTH@,
# so the shell it contains is written exactly as it runs, with no escaping.
#
# Usage:
#   bash scripts/ts5/generate_hook_wrappers.sh          # write
#   bash scripts/ts5/generate_hook_wrappers.sh --check  # report drift, exit 1

set -uo pipefail
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
CHECK="${1:-}"

# wrapper path | hook name | depth from the wrapper to the repository root
WRAPPERS=$(cat <<'EOF'
.claude/hooks/session-start.sh|claude:session-start|../..
.claude/hooks/log-user-prompt.sh|claude:user-prompt|../..
.claude/hooks/log-session-end.sh|claude:session-end|../..
.claude/hooks/mirror-inject.sh|claude:inject|../..
.gemini/hooks/session-start.sh|gemini:session-start|../..
.gemini/hooks/log-user.sh|gemini:log-user|../..
.gemini/hooks/log-assistant.sh|gemini:log-assistant|../..
.gemini/hooks/session-end.sh|gemini:session-end|../..
plugins/mirror-mind/hooks/session-start.sh|claude:session-start|../../..
plugins/mirror-mind/hooks/log-user-prompt.sh|claude:user-prompt|../../..
plugins/mirror-mind/hooks/log-session-end.sh|claude:session-end|../../..
plugins/mirror-mind/hooks/mirror-inject.sh|claude:inject|../../..
EOF
)

TEMPLATE=$(cat <<'EOF'
#!/usr/bin/env bash
# Mirror Mind hook wrapper — GENERATED by scripts/ts5/generate_hook_wrappers.sh.
# Edit the generator, never this file: every wrapper shares these bytes and
# differs only in the hook name and its depth to the repository root
# (CV22.DS10.TS5, decision D4).
#
# Resolve the repository from THIS FILE, never from the cwd: a runtime spawns
# hooks from whatever directory the session is in.
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$HERE/@DEPTH@" && pwd -P)"
HOOK="@HOOK@"

# A hook never fails the user's turn, and never fails in silence: when it
# cannot do its job it appends ONE line to <mirror home>/hooks.log and exits 0.
# The home is found the way the core finds it -- MIRROR_HOME, else
# MIRROR_USER -- each from the environment when set there, else from this
# checkout's .env, as Node's --env-file reads it. A GUI launch carries neither
# variable, and the first wrappers then wrote to a home nobody reads.
env_value() {
  if [ -n "${!1+set}" ]; then printf '%s' "${!1}"; return; fi
  [ -f "$REPO_ROOT/.env" ] || return 0
  sed -n -E "s/^[[:space:]]*(export[[:space:]]+)?$1[[:space:]]*=[[:space:]]*//p" "$REPO_ROOT/.env" \
    | tail -n 1 | tr -d "\"'\r"
}
note() {
  local home user
  home="$(env_value MIRROR_HOME)"
  user="$(env_value MIRROR_USER)"
  if [ -n "$home" ]; then
    home="${home/#\~/$HOME}"
  elif [ -n "$user" ]; then
    home="$HOME/.mirror-minds/$user"
    [ -d "$home" ] || [ ! -d "$HOME/.mirror/$user" ] || home="$HOME/.mirror/$user"
  else
    return 0
  fi
  mkdir -p "$home" 2>/dev/null \
    && printf '%s %s: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$HOOK" "$1" >> "$home/hooks.log" 2>/dev/null
}

# Find Node. /usr/bin/python3 exists on every macOS; node usually lives under
# nvm or Homebrew and is NOT on the PATH of a GUI-launched runtime. The Python
# hooks could end in `|| true` because they always found their interpreter;
# the same silence here would hide a new failure — no logging, no inject, no
# close tail — that a user would meet weeks later as "Mirror stopped
# remembering". So an unresolvable Node is RECORDED, never swallowed.
NODE="${MIRROR_NODE:-}"
if [ -z "$NODE" ] || [ ! -x "$NODE" ]; then
  NODE="$(command -v node 2>/dev/null || true)"
fi
for candidate in "$HOME/.nvm/current/bin/node" /opt/homebrew/bin/node /usr/local/bin/node; do
  [ -n "$NODE" ] && break
  [ -x "$candidate" ] && NODE="$candidate"
done

if [ -z "$NODE" ]; then
  note "node not found on PATH; hook skipped. Set MIRROR_NODE."
  exit 0
fi

# Not `exec`: main.ts exits 0 whatever happens inside it, so a non-zero exit
# means Node itself could not run the hook -- too old for a .ts entry point or
# for --env-file-if-exists, or it crashed. That used to vanish into a stderr no
# runtime shows (TS5 handoff review, finding N1).
"$NODE" --no-warnings --env-file-if-exists="$REPO_ROOT/.env" \
  "$REPO_ROOT/ts/src/hooks/main.ts" "$HOOK" "$@"
status=$?
if [ "$status" -ne 0 ]; then
  note "node exited $status before the hook finished ($NODE, $("$NODE" --version 2>/dev/null || echo 'version unknown')); Mirror needs Node 24 or later. Set MIRROR_NODE."
fi
exit 0
EOF
)

render() {
  local hook="$1" depth="$2" out="$TEMPLATE"
  out="${out//@HOOK@/$hook}"
  out="${out//@DEPTH@/$depth}"
  printf '%s\n' "$out"
}

status=0
while IFS='|' read -r path hook depth; do
  [ -z "$path" ] && continue
  target="$REPO_ROOT/$path"
  rendered="$(render "$hook" "$depth")"
  if [ "$CHECK" = "--check" ]; then
    if [ ! -f "$target" ] || [ "$(cat "$target")" != "$rendered" ]; then
      echo "drift: $path"
      status=1
    fi
  else
    mkdir -p "$(dirname "$target")"
    printf '%s\n' "$rendered" > "$target"
    chmod +x "$target"
  fi
done <<< "$WRAPPERS"

if [ "$CHECK" = "--check" ]; then
  [ "$status" -eq 0 ] && echo "hook wrappers: in sync."
  exit "$status"
fi
echo "hook wrappers: generated."
