#!/usr/bin/env bash
# Mirror Mind hook wrapper — GENERATED by scripts/generate_hook_wrappers.sh.
# Edit the generator, never this file: every wrapper shares these bytes and
# differs only in the hook name and in how it finds the Mirror entry
# (CV22.DS10.TS5 decision D4; CV22.DS10.US3 decision D5).
set -uo pipefail
HOOK="codex:session-start"

# Resolve the tree from THIS FILE, never from the cwd: a runtime spawns hooks
# from whatever directory the session is in. The tree is a checkout or the
# installed package; the wrapper's depth to its root is the same in both.
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd "$HERE/../.." && pwd -P)"

# A hook never fails the user's turn, and never fails in silence: when it
# cannot do its job it appends ONE line to <mirror home>/hooks.log and exits 0.
# The home is found the way the core finds it -- MIRROR_HOME, else
# MIRROR_USER -- from the environment when set there, else from the tree's
# .env when the wrapper is in a tree, else from the user's config file
# (~/.config/mirror/env), in the core's order (US3, D3). A GUI launch carries
# neither variable, and the first wrappers then wrote to a home nobody reads.
env_file_value() {
  [ -f "$2" ] || return 0
  sed -n -E "s/^[[:space:]]*(export[[:space:]]+)?$1[[:space:]]*=[[:space:]]*//p" "$2" \
    | tail -n 1 | tr -d "\"'\r"
}
env_value() {
  local value=""
  if [ -n "${!1+set}" ]; then printf '%s' "${!1}"; return; fi
  [ -z "$REPO_ROOT" ] || value="$(env_file_value "$1" "$REPO_ROOT/.env")"
  [ -n "$value" ] || value="$(env_file_value "$1" "${XDG_CONFIG_HOME:-$HOME/.config}/mirror/env")"
  printf '%s' "$value"
}
note() {
  local home user
  home="$(env_value MIRROR_HOME)"
  user="$(env_value MIRROR_USER)"
  if [ -n "$home" ]; then
    home="${home/#\~/$HOME}"
  elif [ -n "$user" ]; then
    home="$HOME/.mirror-minds/$user"
    [ -d "$home" ] || [ ! -d "$HOME/.mirror/$user" ] || home="$HOME/.mirror/$user"
  else
    return 0
  fi
  mkdir -p "$home" 2>/dev/null \
    && printf '%s %s: %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$HOOK" "$1" >> "$home/hooks.log" 2>/dev/null
}

ENTRY="$REPO_ROOT/bin/mirror-hook.js"

# Find Node. /usr/bin/python3 exists on every macOS; node usually lives under
# nvm or Homebrew and is NOT on the PATH of a GUI-launched runtime. The Python
# hooks could end in `|| true` because they always found their interpreter;
# the same silence here would hide a new failure — no logging, no inject, no
# close tail — that a user would meet weeks later as "Mirror stopped
# remembering". So an unresolvable Node is RECORDED, never swallowed. The
# directory the entry was found in is searched first: an npm global bin holds
# the `node` that installed the package beside `mirror-hook`, while a system
# `/usr/local/bin/node` can be years older (CI's Ubuntu runner has one).
NODE="${MIRROR_NODE:-}"
if [ -z "$NODE" ] || [ ! -x "$NODE" ]; then
  NODE="$(command -v node 2>/dev/null || true)"
fi
for candidate in "$(dirname "$ENTRY")/node" "$HOME/.nvm/current/bin/node" /opt/homebrew/bin/node /usr/local/bin/node; do
  [ -n "$NODE" ] && break
  [ -x "$candidate" ] && NODE="$candidate"
done

if [ -z "$NODE" ]; then
  note "node not found on PATH; hook skipped. Set MIRROR_NODE."
  exit 0
fi

# Not `exec`: the entry exits 0 whatever happens inside it, so a non-zero exit
# means Node itself could not run the hook -- too old for the loader shim, or
# it crashed. That used to vanish into a stderr no runtime shows (TS5 handoff
# review, finding N1). No flags: the entry reads configuration and silences
# its own warnings (US3, D3).
"$NODE" "$ENTRY" "$HOOK" "$@"
status=$?
if [ "$status" -ne 0 ]; then
  note "node exited $status before the hook finished ($NODE, $("$NODE" --version 2>/dev/null || echo 'version unknown')); Mirror needs Node 24 or later. Set MIRROR_NODE."
fi
exit 0
