// CV22.DS10.TS5 slice G — the portable demo database, generated by TypeScript.
//
// `ts/parity/generate_demo_memory_db.py` was the only way to produce the
// synthetic `memory.db` the updater smoke, the hook row-diffs, and the
// Navigator route consume, and plateau 3 deletes the interpreter it ran on.
// These tests pin what the generated database CONTAINS, row by row, so the
// port is graded by its product rather than by its source. The one-time
// cross-engine proof -- both generators, same rows -- is recorded in the story's
// test guide; it could only be run while Python still existed.

import assert from "node:assert/strict";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { after, test } from "node:test";

import { openDatabaseReadOnly } from "#db/database.ts";
import { blobToFloat32 } from "#db/decode.ts";
import { KNOWN_MIGRATION_IDS } from "#db/schemaState.ts";
import {
  DEMO_CONSOLIDATIONS,
  DEMO_JOURNEYS,
  DEMO_MEMORIES,
  DEMO_PERSONAS,
  demoTasks,
  generateDemoMemoryDb,
} from "#smoke/demoMemoryDb.ts";

const roots: string[] = [];
after(() => {
  for (const root of roots) rmSync(root, { recursive: true, force: true });
});

/** A Wednesday, so the week's Monday is two days earlier. Local time. */
const WEDNESDAY = new Date(2026, 8, 23, 10, 0, 0);

function generated(today: Date = WEDNESDAY): string {
  const root = mkdtempSync(join(tmpdir(), "demo-db-"));
  roots.push(root);
  const path = join(root, "home", "memory.db");
  generateDemoMemoryDb(path, { today });
  return path;
}

function rows(path: string, sql: string): Record<string, unknown>[] {
  const db = openDatabaseReadOnly(path);
  try {
    return db.prepare(sql).all() as Record<string, unknown>[];
  } finally {
    db.close();
  }
}

test("the database is current: every known migration is recorded", () => {
  const path = generated();
  const ids = rows(path, "SELECT id FROM _migrations ORDER BY id").map((row) => row.id);
  assert.deepEqual(ids, [...KNOWN_MIGRATION_IDS].sort());
});

test("the six memories carry their declared fields and vectors", () => {
  const path = generated();
  const stored = rows(
    path,
    "SELECT id, title, content, created_at, use_count, relevance_score, memory_type, layer, " +
      "journey, embedding, last_accessed_at, readiness_state, conversation_id, context, " +
      "persona, tags, metadata FROM memories ORDER BY rowid",
  );
  assert.deepEqual(
    stored.map((row) => row.id),
    DEMO_MEMORIES.map((memory) => memory.id),
  );
  for (const [index, memory] of DEMO_MEMORIES.entries()) {
    const row = stored[index] as Record<string, unknown>;
    assert.equal(row.title, memory.title);
    assert.equal(row.content, memory.content);
    assert.equal(row.created_at, memory.createdAt);
    assert.equal(row.use_count, memory.useCount);
    assert.equal(row.relevance_score, memory.relevance);
    assert.equal(row.memory_type, memory.memoryType);
    assert.equal(row.layer, memory.layer);
    assert.equal(row.journey, memory.journey);
    assert.equal(row.last_accessed_at, memory.lastAccessed);
    // Python's `Memory` defaults, which the generator never overrode.
    assert.equal(row.readiness_state, "observed");
    for (const column of ["conversation_id", "context", "persona", "tags", "metadata"]) {
      assert.equal(row[column], null, `${memory.id}.${column}`);
    }
    const vector = Array.from(blobToFloat32(row.embedding as Uint8Array));
    assert.equal(vector.length, 8);
    vector.forEach((value, at) => {
      assert.ok(Math.abs(value - (memory.vector[at] as number)) < 1e-6, `${memory.id}[${at}]`);
    });
  }
});

test("each memory's access log holds access_count rows at its last access", () => {
  const path = generated();
  const log = rows(
    path,
    "SELECT memory_id, accessed_at, access_context FROM memory_access_log ORDER BY id",
  );
  const expected = DEMO_MEMORIES.flatMap((memory) =>
    Array.from({ length: memory.accessCount }, () => ({
      memory_id: memory.id,
      accessed_at: memory.lastAccessed,
      access_context: "demo-parity",
    })),
  );
  assert.deepEqual(log, expected);
});

test("personas carry routing keywords in Python's JSON dialect", () => {
  const path = generated();
  const personas = rows(
    path,
    "SELECT key, content, version, metadata FROM identity WHERE layer = 'persona' ORDER BY rowid",
  );
  assert.deepEqual(
    personas,
    DEMO_PERSONAS.map(([key, keywords]) => ({
      key,
      content: `Synthetic persona ${key} for parity fixtures.`,
      version: "1.0.0",
      metadata: `{"routing_keywords": [${keywords.map((k) => `"${k}"`).join(", ")}]}`,
    })),
  );
});

test("journeys keep the malformed hierarchy, in metadata and in the parent column", () => {
  const path = generated();
  const journeys = rows(
    path,
    "SELECT key, content, metadata, parent_journey FROM identity WHERE layer = 'journey' ORDER BY rowid",
  );
  assert.deepEqual(
    journeys,
    DEMO_JOURNEYS.map(([key, content, parent]) => ({
      key,
      content,
      metadata: parent === null ? null : `{"parent_journey": "${parent}"}`,
      // What migrate-on-open's backfill gives a Python-written database, and
      // what the hierarchy readers see: the orphan and the loop stay broken.
      parent_journey: parent,
    })),
  );
});

test("tasks are dated relative to the week that contains `today`", () => {
  const path = generated();
  const tasks = rows(
    path,
    "SELECT id, journey, title, status, due_date, scheduled_at, stage, source, completed_at, " +
      "time_hint, context, metadata FROM tasks ORDER BY rowid",
  );
  assert.deepEqual(
    tasks.map((task) => [task.id, task.status, task.due_date, task.scheduled_at]),
    [
      ["demo-task-mon", "todo", "2026-09-21", null],
      ["demo-task-wed-scheduled", "doing", null, "2026-09-23T14:00"],
      ["demo-task-thu-done", "done", "2026-09-24", null],
      ["demo-task-fri-blocked", "blocked", "2026-09-25", null],
      ["demo-task-next-week", "todo", "2026-09-28", null],
      ["demo-task-last-week-done", "done", "2026-09-15", null],
    ],
  );
  assert.equal(tasks[0]?.stage, "Setup");
  assert.equal(tasks[3]?.journey, null);
  for (const task of tasks) {
    assert.equal(task.source, "manual");
    // A `done` task with no completion time is what the Python generator wrote;
    // the fixture is not a status transition, and the port does not invent one.
    assert.equal(task.completed_at, null);
    assert.equal(task.time_hint, null);
    assert.equal(task.context, null);
    assert.equal(task.metadata, null);
  }
  assert.deepEqual(
    demoTasks(WEDNESDAY).map((task) => task.id),
    tasks.map((task) => task.id),
  );
});

test("a Sunday belongs to the week that started six days before it", () => {
  const sunday = new Date(2026, 8, 27, 23, 30, 0);
  assert.equal(demoTasks(sunday)[0]?.due_date, "2026-09-21");
});

test("consolidations are written exactly as declared", () => {
  const path = generated();
  const stored = rows(
    path,
    "SELECT id, action, proposal, result, source_memory_ids, target_layer, target_key, " +
      "rationale, status, created_at, reviewed_at FROM consolidations ORDER BY rowid",
  );
  assert.deepEqual(
    stored,
    DEMO_CONSOLIDATIONS.map((row) => ({ ...row, result: null, reviewed_at: null })),
  );
});

test("regenerating replaces the database rather than appending to it", () => {
  // Appending would collide on the fixed memory ids and throw, so a second
  // run that succeeds with the same counts is a run that started from nothing.
  const path = generated();
  generateDemoMemoryDb(path, { today: WEDNESDAY });
  assert.equal(rows(path, "SELECT id FROM memories").length, DEMO_MEMORIES.length);
  assert.equal(rows(path, "SELECT id FROM identity").length, 12);
  assert.equal(rows(path, "PRAGMA integrity_check")[0]?.integrity_check, "ok");
});
