// CV22.DS7.US10 slice E — Pi and Codex session backfill parity.
//
// Both imports are graded as resulting database state over the committed
// fixture corpus, against `backfill.golden.json` generated by the Python
// oracle. The corpus pins the walk order (path components, not strings),
// every timestamp form, whole-file skips on corrupt or structurally invalid
// input, and the title asymmetry between the two importers.
//
// The import-vs-live-hook race (resolved decision 4B) is proven the way the
// Python fix was: a second writer holds the lock, binds the session while the
// backfill waits, and must keep its binding.

import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { copyFileSync, mkdirSync, mkdtempSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
import {
  backfillCodexSession,
  backfillPiSessions,
  parsePiContent,
  parsePiTimestamp,
  resolvePiSessionsDir,
} from "#conversation/backfill.ts";
import { openDatabaseCopyForWrite, type WritableDatabase } from "#db/database.ts";
import {
  CODEX_DIR,
  frozenDeps,
  backfillGolden as golden,
  PI_SESSIONS_DIR,
  seedTrackedSession,
  snapshotState,
} from "#helpers/backfillFixture.ts";
import { createRuntimeTables } from "#helpers/runtimeSchema.ts";

function fixture(): { db: WritableDatabase; dir: string } {
  const dir = mkdtempSync("/tmp/backfill-");
  const db = openDatabaseCopyForWrite(join(dir, "copy.db"));
  createRuntimeTables(db);
  return { db, dir };
}

// --- Pi sessions directory walk ---

test("backfillPiSessions imports the fixture corpus exactly as Python does", () => {
  const { db, dir } = fixture();
  const deps = frozenDeps();
  seedTrackedSession(db, join(PI_SESSIONS_DIR, "tracked.jsonl"), "pi");

  const count = backfillPiSessions(db, { sessionsDir: PI_SESSIONS_DIR }, deps);
  assert.equal(count, golden.pi_sessions.first_count);
  assert.deepEqual(snapshotState(db, PI_SESSIONS_DIR), golden.pi_sessions.state);

  // Every imported session is now tracked, so the walk is idempotent.
  assert.equal(
    backfillPiSessions(db, { sessionsDir: PI_SESSIONS_DIR }, deps),
    golden.pi_sessions.rerun_count,
  );
  assert.equal(
    backfillPiSessions(db, { sessionsDir: join(dir, "absent") }, deps),
    golden.pi_sessions.absent_dir_count,
  );
  db.close();
});

test("the Pi walk is ordered by path components: a/b.jsonl before a-x/c.jsonl", () => {
  // Pinned separately from the full snapshot so a reordering failure names
  // the property rather than dumping two states.
  const order = golden.pi_sessions.state.runtime_sessions
    .map((session) => session.session_id)
    .filter((id) => id !== "<sessions_dir>/tracked.jsonl");
  assert.deepEqual(order, [
    "<sessions_dir>/a/b.jsonl",
    "<sessions_dir>/a-x/c.jsonl",
    "<sessions_dir>/emoji-title.jsonl",
    "<sessions_dir>/nested/deeper/d.jsonl",
  ]);
  assert.ok(
    ["a-x/c.jsonl", "a/b.jsonl"].sort()[0] === "a-x/c.jsonl",
    "precondition: a string sort would reverse the first two",
  );
});

test("parsePiTimestamp reproduces every form Python accepts", () => {
  const now = () => "<now>";
  assert.equal(parsePiTimestamp(1713348000000, now), "2024-04-17T10:00:00+00:00");
  assert.equal(parsePiTimestamp(1713348000123, now), "2024-04-17T10:00:00.123000+00:00");
  assert.equal(parsePiTimestamp(1713348000123.7, now), "2024-04-17T10:00:00.123700+00:00");
  assert.equal(parsePiTimestamp("2026-04-17T10:00:00Z", now), "2026-04-17T10:00:00Z");
  // A seconds epoch is below Python's 1e10 gate; bool is an int that never
  // clears it; null and absent fall through.
  assert.equal(parsePiTimestamp(1713348000, now), "<now>");
  assert.equal(parsePiTimestamp(true, now), "<now>");
  assert.equal(parsePiTimestamp(null, now), "<now>");
  assert.equal(parsePiTimestamp(undefined, now), "<now>");
});

test("parsePiContent joins text blocks with a newline and ignores the rest", () => {
  assert.equal(parsePiContent("plain"), "plain");
  assert.equal(
    parsePiContent([
      { type: "text", text: "a" },
      { type: "tool_use", name: "x" },
      "stray",
      { type: "text" },
      { type: "text", text: "b" },
    ]),
    "a\n\nb",
  );
  assert.equal(parsePiContent(42), "");
  assert.equal(parsePiContent({ type: "text", text: "dict" }), "");
  assert.throws(() => parsePiContent([{ type: "text", text: 123 }]), TypeError);
});

test("resolvePiSessionsDir follows Python's order: argument, PI_SESSIONS_DIR, ~/.pi", () => {
  const home = "/home/navigator";
  assert.equal(
    resolvePiSessionsDir("/explicit", { PI_SESSIONS_DIR: "/from-env" }, home),
    "/explicit",
  );
  assert.equal(resolvePiSessionsDir(null, { PI_SESSIONS_DIR: "/from-env" }, home), "/from-env");
  assert.equal(resolvePiSessionsDir("", {}, home), "/home/navigator/.pi/agent/sessions");
  assert.equal(
    resolvePiSessionsDir(undefined, { PI_SESSIONS_DIR: "" }, home),
    join(home, ".pi", "agent", "sessions"),
  );
});

// --- Codex single-file imports ---

test("backfillCodexSession imports the fixture corpus exactly as Python does", () => {
  const { db } = fixture();
  const deps = frozenDeps();
  seedTrackedSession(db, "codex-tracked-0006", "codex");

  for (const scenario of golden.codex.cases) {
    const count = backfillCodexSession(
      db,
      { jsonlPath: join(CODEX_DIR, scenario.file), interface: scenario.interface },
      deps,
    );
    assert.equal(count, scenario.count, scenario.label);
  }

  // A kept event without a timestamp fails model validation in Python inside
  // the import transaction; nothing is written on either side.
  const before = db.prepare("SELECT COUNT(*) AS c FROM conversations").get()?.c;
  assert.equal(golden.codex.null_timestamp.raises, true);
  assert.throws(
    () => backfillCodexSession(db, { jsonlPath: join(CODEX_DIR, "null-timestamp.jsonl") }, deps),
    TypeError,
  );
  assert.equal(db.prepare("SELECT COUNT(*) AS c FROM conversations").get()?.c, before);
  assert.equal(golden.codex.null_timestamp.rows_unchanged, true);

  assert.deepEqual(snapshotState(db), golden.codex.state);
  db.close();
});

test("the two importers title differently, and that asymmetry is Python's", () => {
  const pi = golden.pi_sessions.state.conversations[0];
  const codex = golden.codex.state.conversations[0];
  assert.ok(pi && codex);
  // Pi: cut to 60 code points, whitespace collapsed, provenance recorded.
  assert.equal(pi.title, "How do I configure the café server for the nomad worksho");
  assert.equal(pi.metadata_raw, '{"title_source": "first_user", "title_status": "provisional"}');
  // Codex: word-boundary cut with an ellipsis, bare column write, no metadata.
  assert.equal(codex.title, "Please review the persistence layer of the port and tell me...");
  assert.equal(codex.metadata_raw, null);
});

// --- Resolved decision 4B: import vs live-hook race ---

const LOCK_HOLDER = join(import.meta.dirname, "backfillLockHolderWorker.ts");

function spawnLockHolder(
  dbPath: string,
  sessionId: string,
): Promise<{ locked: Promise<void>; done: Promise<number | null> }> {
  return new Promise((resolveSpawn) => {
    const child = spawn(process.execPath, [LOCK_HOLDER, dbPath, sessionId], {
      env: { ...process.env, NODE_OPTIONS: "--no-warnings" },
    });
    let stderr = "";
    child.stderr.on("data", (chunk) => {
      stderr += String(chunk);
    });
    const locked = new Promise<void>((resolveLocked, reject) => {
      child.stdout.on("data", (chunk) => {
        if (String(chunk).includes("locked")) resolveLocked();
      });
      child.on("error", reject);
    });
    const done = new Promise<number | null>((resolveDone) => {
      child.on("close", (code) => {
        if (code !== 0) console.error(`lock holder stderr: ${stderr}`);
        resolveDone(code);
      });
    });
    resolveSpawn({ locked, done });
  });
}

test("a binding won by a live hook while the import waits for the lock survives the backfill", async () => {
  const { db, dir } = fixture();
  const sessionsDir = join(dir, "sessions");
  mkdirSync(sessionsDir);
  copyFileSync(
    join(PI_SESSIONS_DIR, "nested", "deeper", "d.jsonl"),
    join(sessionsDir, "race.jsonl"),
  );
  const sessionId = join(sessionsDir, "race.jsonl");

  const holder = await spawnLockHolder(join(dir, "copy.db"), sessionId);
  await holder.locked;

  // The pre-check reads past the RESERVED lock and sees no binding; the import
  // then blocks on BEGIN IMMEDIATE until the hook commits, and must re-check.
  const count = backfillPiSessions(db, { sessionsDir }, frozenDeps());
  assert.equal(await holder.done, 0);

  assert.equal(count, 0);
  const session = db.prepare("SELECT * FROM runtime_sessions WHERE session_id = ?").get(sessionId);
  assert.equal(session?.conversation_id, "conv-live");
  assert.equal(session?.active, 1);
  assert.equal(session?.closed_at, null);
  assert.deepEqual(
    db
      .prepare("SELECT id FROM conversations")
      .all()
      .map((row) => row.id),
    ["conv-live"],
  );
  db.close();
});
