"""Generate committed migration-transition fixtures for CV22.DS6.TS2 (Track B).

Checkpoint N's "pre-state" fixture is the database exactly as it exists after
migrations 1..(N-1) have been applied for real via Python's own MIGRATIONS
functions (the frozen oracle) — so migration N's real transition logic is
genuinely exercised when the ported (TS) and oracle (Python) engines each run
forward from that seed, rather than testing an empty-table edge case that
never occurs on a real installed database. Representative rows are inserted
between certain steps so rename/backfill logic acts on real pre-existing data.

Checkpoints are generated by a SINGLE forward cascade from one hand-authored
genesis seed (the oldest addressable legacy shape, pre-migration-001) — not
nine independently hand-crafted seeds. This mirrors how a real database's
history actually looks (genesis -> 1 -> 2 -> ... -> 16), gives the multi-hop
fixture "for free" as the final step of the same cascade, and keeps the nine
checkpoints DRY.

Known gap (see CV22.DS6.TS2 done.md / debt review): migration 016's real
ADD-COLUMN-if-missing + backfill-against-NULL-rows branches cannot be reached
by this cascade, because the CURRENT migration 015 already creates
`display_code TEXT NOT NULL` inline — there are no pre-existing NULL rows by
the time the cascade reaches checkpoint 016. Exercising 016's real logic needs
a separately hand-authored fixture representing a database created by an
OLDER version of migration 015 (before display_code existed there), which is
out of this generator's scope.

Two fixture kinds are committed per checkpoint, under ts/test/fixtures/migrations/:
- `migration-<NNN>-pre-state.sql` (or `migration-chain-multi-hop-pre-state.sql`):
  a portable SQL script (CREATE TABLE + INSERT + partial `_migrations` ledger)
  executable identically by Python (`executescript`) and TS (`node:sqlite`'s
  `.exec()`).
- `migration-<NNN>-expected.json`: captured by running Python's REAL
  `run_migrations` forward from that seed to completion (migration 16) —
  schema inventory (reusing `schema_inventory.build_schema_inventory`), the
  full `_migrations` id set, and fixture-specific row-level facts.

Regenerate via: uv run python ts/parity/generate_migration_fixtures.py
"""

from __future__ import annotations

import json
import sqlite3
from pathlib import Path

from memory.db.migrations import MIGRATIONS, run_migrations
from memory.db.schema_inventory import (
    _is_fts_shadow_table,
    _virtual_table_names,
    build_schema_inventory,
)
from memory.models import _now

FIXTURES_DIR = Path(__file__).resolve().parents[2] / "ts" / "test" / "fixtures" / "migrations"

GENESIS_SQL = """
CREATE TABLE conversations (
    id TEXT PRIMARY KEY,
    title TEXT,
    started_at TEXT NOT NULL,
    ended_at TEXT,
    interface TEXT NOT NULL,
    persona TEXT,
    project TEXT,
    summary TEXT,
    tags TEXT,
    metadata TEXT
);

CREATE TABLE memories (
    id TEXT PRIMARY KEY,
    conversation_id TEXT REFERENCES conversations(id),
    memory_type TEXT NOT NULL,
    layer TEXT NOT NULL DEFAULT 'ego',
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    context TEXT,
    project TEXT,
    persona TEXT,
    tags TEXT,
    created_at TEXT NOT NULL,
    relevance_score REAL DEFAULT 1.0,
    embedding BLOB,
    metadata TEXT
);

CREATE INDEX idx_memories_project ON memories(project);

CREATE TABLE identity (
    id TEXT PRIMARY KEY,
    layer TEXT NOT NULL,
    key TEXT NOT NULL,
    content TEXT NOT NULL,
    version TEXT DEFAULT '1.0.0',
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    metadata TEXT,
    UNIQUE(layer, key)
);

INSERT INTO conversations (id, title, started_at, interface, persona, project)
VALUES ('conv-legacy-1', 'Legacy Conversation', '2025-01-10T09:00:00Z', 'cli', 'engineer', 'genesis-project');

INSERT INTO memories (id, conversation_id, memory_type, layer, title, content, context, project, created_at)
VALUES ('mem-legacy-1', 'conv-legacy-1', 'decision', 'ego', 'Legacy Decision', 'Keep the legacy content intact through every migration.', 'legacy-context', 'genesis-project', '2025-01-10T09:05:00Z');

INSERT INTO identity (id, layer, key, content, created_at, updated_at)
VALUES ('ident-legacy-1', 'project', 'genesis-project', '# Legacy Project Identity', '2025-01-10T09:10:00Z', '2025-01-10T09:10:00Z');
"""

# Extra rows inserted right after a migration creates a table, so later
# rename/backfill migrations have real pre-existing rows to act on — not just
# an empty table.
POST_MIGRATION_INSERTS: dict[str, str] = {
    "002_create_attachments": """
        INSERT INTO attachments (id, travessia_id, name, content, created_at, updated_at)
        VALUES ('att-legacy-1', 'genesis-project', 'legacy-plan.md', 'Legacy plan content.', '2025-01-10T09:15:00Z', '2025-01-10T09:15:00Z');
    """,
    "003_create_tasks": """
        INSERT INTO tasks (id, travessia, title, status, source, created_at, updated_at)
        VALUES ('task-legacy-1', 'genesis-project', 'Legacy task', 'todo', 'manual', '2025-01-10T09:20:00Z', '2025-01-10T09:20:00Z');
    """,
}

# --- CV22.DS6.TS5: the hand-authored migration-016 legacy fixture ---
#
# The cascade cannot reach 016's real ADD-COLUMN + backfill branches (current 015
# inlines display_code NOT NULL). This seed reconstructs a database created by an
# OLDER 015 — derived authoritatively from migration 016's OWN operations: 016
# ADDs display_code and creates the two ux_..._display_code indexes, so old-015 is
# current 015 minus exactly those. All timestamps are frozen so this fixture is
# byte-reproducible (unlike the wall-clock cascade seeds).
#
# Provenance note: git history folds 015+016 into one squashed commit, so the
# old-015 shape is derived from 016's diff, not read from history. If 015/016
# shipped together this exercises a defensive/never-on-fresh branch — the fixture
# is a regression guard for it, not proof of a live migration path.
FROZEN_MIGRATION_TS = "2026-01-01T00:00:00.000000Z"

OLD_015_BUILDER_WORKBENCH_SQL = """
    CREATE TABLE IF NOT EXISTS builder_refinement_stories (
        id TEXT PRIMARY KEY,
        journey TEXT NOT NULL,
        title TEXT NOT NULL,
        description TEXT,
        status TEXT NOT NULL DEFAULT 'draft',
        position INTEGER NOT NULL DEFAULT 0,
        source TEXT NOT NULL DEFAULT 'manual',
        provenance TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        pulled_at TEXT,
        closed_at TEXT,
        CHECK(status IN ('draft', 'open', 'active', 'closed', 'parked'))
    );
    CREATE INDEX IF NOT EXISTS idx_builder_refinement_stories_journey_status
        ON builder_refinement_stories(journey, status, position, updated_at);

    CREATE TABLE IF NOT EXISTS builder_change_requests (
        id TEXT PRIMARY KEY,
        journey TEXT NOT NULL,
        refinement_story_id TEXT REFERENCES builder_refinement_stories(id),
        title TEXT NOT NULL,
        body TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'captured',
        position INTEGER NOT NULL DEFAULT 0,
        source TEXT NOT NULL DEFAULT 'manual',
        provenance TEXT,
        outcome_notes TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        completed_at TEXT,
        CHECK(status IN (
            'captured', 'planned', 'active', 'implemented', 'validated',
            'done', 'parked', 'rejected', 'promoted'
        ))
    );
    CREATE INDEX IF NOT EXISTS idx_builder_change_requests_story_status
        ON builder_change_requests(journey, refinement_story_id, status, position, updated_at);
    CREATE INDEX IF NOT EXISTS idx_builder_change_requests_journey_status
        ON builder_change_requests(journey, status, updated_at);

    CREATE TABLE IF NOT EXISTS builder_refinement_cursors (
        journey TEXT PRIMARY KEY,
        active_refinement_story_id TEXT REFERENCES builder_refinement_stories(id),
        active_change_request_id TEXT REFERENCES builder_change_requests(id),
        last_refinement_event TEXT,
        updated_at TEXT NOT NULL
    );
"""

# Two journeys with NULL display_code, exercising per-journey code reset and the
# migration's ORDER BY (RS: position; CR: created_at). Expected backfill:
#   alpha: rs-alpha-1->RS001, rs-alpha-2->RS002; beta: rs-beta-1->RS001
#   alpha: cr-alpha-1->CR001, cr-alpha-2->CR002; beta: cr-beta-1->CR001
BUILDER_WORKBENCH_LEGACY_ROWS = """
    INSERT INTO builder_refinement_stories (id, journey, title, position, created_at, updated_at) VALUES
        ('rs-alpha-1', 'alpha-journey', 'Alpha refinement one', 0, '2026-01-02T00:00:00Z', '2026-01-02T00:00:00Z'),
        ('rs-alpha-2', 'alpha-journey', 'Alpha refinement two', 1, '2026-01-02T00:00:01Z', '2026-01-02T00:00:01Z'),
        ('rs-beta-1', 'beta-journey', 'Beta refinement one', 0, '2026-01-02T00:00:02Z', '2026-01-02T00:00:02Z');
    INSERT INTO builder_change_requests (id, journey, refinement_story_id, title, body, position, created_at, updated_at) VALUES
        ('cr-alpha-1', 'alpha-journey', 'rs-alpha-1', 'Alpha change one', 'Body a1', 0, '2026-01-03T00:00:00Z', '2026-01-03T00:00:00Z'),
        ('cr-alpha-2', 'alpha-journey', 'rs-alpha-1', 'Alpha change two', 'Body a2', 1, '2026-01-03T00:00:01Z', '2026-01-03T00:00:01Z'),
        ('cr-beta-1', 'beta-journey', 'rs-beta-1', 'Beta change one', 'Body b1', 0, '2026-01-03T00:00:02Z', '2026-01-03T00:00:02Z');
"""

# Checkpoints committed as "pre-state" fixtures: captured immediately BEFORE
# the named migration runs (i.e., after exactly the preceding migrations have
# been applied). 016 is a known, documented gap — see module docstring.
CHECKPOINTS = [
    "001_project_to_travessia",
    "002_create_attachments",
    "003_create_tasks",
    "004_tasks_temporal_fields",
    "005_travessia_to_journey",
    "008_create_memories_fts",
    "009_memories_reinforcement_columns",
]


def _sql_literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value)
    if isinstance(value, bytes):
        return "X'" + value.hex() + "'"
    escaped = str(value).replace("'", "''")
    return f"'{escaped}'"


def _dump_sql(conn: sqlite3.Connection) -> str:
    """Dump the connection as portable SQL: all CREATE statements first (in
    sqlite_master's dependency-safe creation order), then all table data as
    INSERT statements.

    Deliberately NOT `conn.iterdump()`: its per-table interleaved schema+data
    grouping can order a table's INSERT before a virtual table its triggers
    reference (e.g. `memories`' data before `memories_fts`'s CREATE, if
    grouped alphabetically), which fires the AFTER-INSERT trigger against a
    not-yet-existing table on replay. Two-phase (all CREATEs, then all
    INSERTs) avoids this entirely: every trigger's target already exists by
    the time any data is replayed.

    FTS5-internal shadow tables are excluded from both phases — they are
    recreated automatically as a side effect of their owning virtual table's
    own CREATE VIRTUAL TABLE statement (see schema_inventory.py, which excludes
    them from structural comparison for the same reason).
    """
    objects = conn.execute(
        "SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL ORDER BY rowid"
    ).fetchall()
    virtual_tables = _virtual_table_names(conn)

    lines: list[str] = ["PRAGMA foreign_keys=OFF;"]
    for obj_type, name, sql in objects:
        if obj_type == "table" and _is_fts_shadow_table(name, virtual_tables):
            continue
        lines.append(sql.rstrip().rstrip(";") + ";")

    tables = [
        name
        for obj_type, name, _sql in objects
        if obj_type == "table" and not _is_fts_shadow_table(name, virtual_tables)
    ]
    for table in tables:
        columns = [row[1] for row in conn.execute(f'PRAGMA table_info("{table}")').fetchall()]
        if not columns:
            continue
        column_list = ", ".join(f'"{c}"' for c in columns)
        for row in conn.execute(f'SELECT {column_list} FROM "{table}"').fetchall():
            values = ", ".join(_sql_literal(value) for value in row)
            lines.append(f'INSERT INTO "{table}" ({column_list}) VALUES ({values});')
    lines.append("PRAGMA foreign_keys=ON;")
    return "\n".join(lines)


def _row_dict(row: sqlite3.Row | None) -> dict | None:
    return dict(row) if row is not None else None


def _display_codes(conn: sqlite3.Connection, table: str) -> list[dict]:
    """The (journey, display_code) pairs a table carries, ordered by id. Empty
    when the table has no rows (every non-016 fixture)."""
    try:
        rows = conn.execute(f"SELECT journey, display_code FROM {table} ORDER BY id").fetchall()
    except sqlite3.OperationalError:
        return []
    return [{"journey": row["journey"], "display_code": row["display_code"]} for row in rows]


def _capture_expected(seed_sql: str) -> dict:
    """Run the REAL Python engine forward to completion from this seed;
    capture the schema inventory, the full applied-id set, and row-level facts
    relevant to Track B's acceptance criteria."""
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(seed_sql)
    run_migrations(conn)

    inventory = build_schema_inventory(conn)
    applied = sorted(row["id"] for row in conn.execute("SELECT id FROM _migrations"))
    identity_layers = sorted(
        row["layer"] for row in conn.execute("SELECT layer FROM identity ORDER BY layer")
    )
    conversation_journeys = [
        row["journey"] for row in conn.execute("SELECT journey FROM conversations ORDER BY id")
    ]
    memory_journeys = [
        row["journey"] for row in conn.execute("SELECT journey FROM memories ORDER BY id")
    ]
    memory_legacy_row = _row_dict(
        conn.execute(
            "SELECT title, content, use_count, readiness_state, journey "
            "FROM memories WHERE id = 'mem-legacy-1'"
        ).fetchone()
    )
    attachment_row = _row_dict(
        conn.execute(
            "SELECT journey_id, name, content FROM attachments WHERE id = 'att-legacy-1'"
        ).fetchone()
    )
    task_row = _row_dict(
        conn.execute(
            "SELECT journey, title, status FROM tasks WHERE id = 'task-legacy-1'"
        ).fetchone()
    )
    fts_hits = [
        row["rowid"]
        for row in conn.execute("SELECT rowid FROM memories_fts WHERE memories_fts MATCH 'legacy'")
    ]
    rs_codes = _display_codes(conn, "builder_refinement_stories")
    cr_codes = _display_codes(conn, "builder_change_requests")
    conn.close()
    expected = {
        "tables": inventory["tables"],
        "indexes": inventory["indexes"],
        "triggers": inventory["triggers"],
        "applied_migration_ids": applied,
        "identity_layers": identity_layers,
        "conversation_journeys": conversation_journeys,
        "memory_journeys": memory_journeys,
        "memory_legacy_row": memory_legacy_row,
        "attachment_legacy_row": attachment_row,
        "task_legacy_row": task_row,
        "memories_fts_findable_legacy_row_count": len(fts_hits),
    }
    # Present only when the builder-workbench tables actually carry rows (the 016
    # legacy fixture) — so every other fixture's expected JSON is unchanged.
    if rs_codes:
        expected["builder_refinement_story_codes"] = rs_codes
    if cr_codes:
        expected["builder_change_request_codes"] = cr_codes
    return expected


def _write_fixture(stem: str, seed_sql: str) -> None:
    expected = _capture_expected(seed_sql)
    (FIXTURES_DIR / f"migration-{stem}-pre-state.sql").write_text(seed_sql, encoding="utf-8")
    (FIXTURES_DIR / f"migration-{stem}-expected.json").write_text(
        json.dumps(expected, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def _write_016_fixture() -> None:
    """Hand-authored migration-016 legacy fixture (CV22.DS6.TS5).

    Runs genesis -> 001..014 for real, then installs the OLD-015 builder-workbench
    shape (no display_code / no ux indexes, derived from migration 016's own
    operations), marks 015 applied, and seeds NULL-display_code RS/CR rows across
    two journeys. Running the real engine forward from this seed makes 016's
    ADD-COLUMN + backfill branches genuinely execute; `_capture_expected` records
    the backfilled codes for the TS parity test to grade.
    """
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(GENESIS_SQL)
    conn.execute(
        "CREATE TABLE IF NOT EXISTS _migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)"
    )
    conn.commit()

    for migration_id, apply in MIGRATIONS:
        if migration_id == "015_create_builder_workbench":
            break
        apply(conn)
        conn.execute(
            "INSERT OR IGNORE INTO _migrations (id, applied_at) VALUES (?, ?)",
            (migration_id, FROZEN_MIGRATION_TS),
        )
        conn.commit()
        if migration_id in POST_MIGRATION_INSERTS:
            conn.executescript(POST_MIGRATION_INSERTS[migration_id])
            conn.commit()

    conn.executescript(OLD_015_BUILDER_WORKBENCH_SQL)
    conn.execute(
        "INSERT OR IGNORE INTO _migrations (id, applied_at) VALUES (?, ?)",
        ("015_create_builder_workbench", FROZEN_MIGRATION_TS),
    )
    conn.executescript(BUILDER_WORKBENCH_LEGACY_ROWS)
    conn.commit()

    seed_sql = _dump_sql(conn)
    conn.close()
    _write_fixture("016", seed_sql)


def generate() -> None:
    FIXTURES_DIR.mkdir(parents=True, exist_ok=True)

    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(GENESIS_SQL)
    conn.commit()

    _write_fixture("chain-multi-hop", GENESIS_SQL)

    conn.execute(
        "CREATE TABLE IF NOT EXISTS _migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL)"
    )
    conn.commit()

    for migration_id, apply in MIGRATIONS:
        if migration_id in CHECKPOINTS:
            stem = migration_id.split("_", 1)[0]
            _write_fixture(stem, _dump_sql(conn))

        apply(conn)
        conn.execute(
            "INSERT OR IGNORE INTO _migrations (id, applied_at) VALUES (?, ?)",
            (migration_id, _now()),
        )
        conn.commit()

        if migration_id in POST_MIGRATION_INSERTS:
            conn.executescript(POST_MIGRATION_INSERTS[migration_id])
            conn.commit()

    conn.close()


if __name__ == "__main__":
    import sys

    if "--only-016" in sys.argv:
        _write_016_fixture()
        print(f"Generated migration-016 fixture under {FIXTURES_DIR}")
    else:
        generate()
        _write_016_fixture()
        print(f"Generated fixtures under {FIXTURES_DIR}")
